### ISSUE TITLE
Status about  ongoing developments 

### ISSUE THREAD

**Issue by abdullegend** [QSolutionsLLC/cornerstone-vtk-mpr#3]
Dear contributors,
Are you guys wirking for next release or update in this project?

**Comment by dannyrb** [comment]
:wave: Hello @abdullegend,

While this was a fun experiment, I've moved on to using the VTK.js implementation described in `react-vtkjs-viewport`. It is consumed by `OHIF/Viewers`, and I think the better approach for most situations. The only exception being situations in which you do not have a GPU (or a reliable GPU) and need to do this kind of work on the CPU.
